In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("combined_concrete_data.csv")

df.head()

,binder,extra water,alkaline solution,molarity of mix,fine aggregate,coarse aggregate,age,curing temperature,compressive strength,water,pozzolan,foaming agent,density,concrete type,water binder ratio
0,428.0,43.0,171.0,14.0,630.0,1170.0,1.0,75.0,30.0,NaN,NaN,NaN,NaN,0,0.500000
1,444.0,43.0,155.0,14.0,630.0,1170.0,1.0,75.0,30.0,NaN,NaN,NaN,NaN,0,0.445946
2,428.0,43.0,171.0,14.0,630.0,1170.0,1.0,75.0,40.0,NaN,NaN,NaN,NaN,0,0.500000
3,428.0,43.0,171.0,14.0,630.0,1170.0,1.0,75.0,28.0,NaN,NaN,NaN,NaN,0,0.500000
4,428.0,43.0,171.0,14.0,630.0,1170.0,2.0,75.0,32.0,NaN,NaN,NaN,NaN,0,0.500000

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
binder,2600.0,444.672208,136.268401,107.200000,400.000000,405.000000,468.000000,992.800000
extra water,1691.0,17.955802,26.448564,0.000000,0.000000,0.000000,32.000000,128.570000
alkaline solution,1691.0,187.283390,36.738527,106.680000,160.020000,180.000000,200.000000,294.400000
molarity of mix,1691.0,11.519456,2.776044,4.100000,10.000000,12.000000,14.000000,20.000000
fine aggregate,2600.0,631.342854,178.804817,0.000000,550.000000,645.000000,697.400000,1098.000000
coarse aggregate,1691.0,1099.968297,188.269756,647.800000,989.500000,1181.000000,1220.350000,1369.000000
age,2600.0,25.490000,22.438885,1.000000,7.000000,28.000000,28.000000,91.000000
curing temperature,1691.0,34.972797,16.904233,20.000000,27.000000,27.000000,28.000000,80.000000
compressive strength,2600.0,29.266384,21.230027,0.080000,10.422500,26.735575,43.745000,110.000000
water,909.0,232.404999,83.601458,68.900000,169.000000,234.000000,290.325000,484.000000
pozzolan,909.0,27.071903,53.917232,0.000000,0.000000,0.000000,25.000000,232.500000
foaming agent,909.0,22.998196,11.927022,0.170000,14.100000,22.800000,31.900000,46.300000
density,909.0,1340.464532,434.200807,497.000000,1000.000000,1400.000000,1725.040000,2009.480000
concrete type,2600.0,0.349615,0.476940,0.000000,0.000000,0.000000,1.000000,1.000000
water binder ratio,2600.0,0.500051,0.143300,0.250526,0.400626,0.471111,0.548255,1.777778

I am going to train with the models, which innately support NANs in the dataset(lightgbm, xgboost), and then impute 0 valuse to the NANs and train other models.

In [4]:
target = "compressive strength"

X = df.drop(columns=[target])
y = df[target]

In [5]:
from sklearn.model_selection import train_test_split

# 80/20 split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,
    stratify=df['concrete type'] 
)

In [6]:
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

Train: (2080, 14), Test: (520, 14)

In [7]:
import warnings
warnings.filterwarnings('ignore', message='X does not have valid feature names')

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import pandas as pd

# ==========================================
# PATH 1: For XGBoost / LightGBM / CatBoost 
# Objective: Scale the data, but PRESERVE NaNs
# ==========================================
scaler_nan = StandardScaler()

X_train = pd.DataFrame(scaler_nan.fit_transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(scaler_nan.transform(X_test), columns=X_test.columns)


# ==========================================
# PATH 2: For Random Forest / Gradient Boosting 
# Objective: TRUE Zero Imputation, THEN scale
# ==========================================
imputer_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
    ('scaler', StandardScaler())
])

X_train_imputed = pd.DataFrame(imputer_pipeline.fit_transform(X_train), columns=X_train.columns)
X_test_imputed = pd.DataFrame(imputer_pipeline.transform(X_test), columns=X_test.columns)

print(f"Path 1 (NaNs Preserved) -> Train: {X_train.shape}, Test: {X_test.shape}")
print(f"Path 2 (Zero Imputed)   -> Train: {X_train_imputed.shape}, Test: {X_test_imputed.shape}")

Path 1 (NaNs Preserved) -> Train: (2080, 14), Test: (520, 14)
Path 2 (Zero Imputed)   -> Train: (2080, 14), Test: (520, 14)

In [12]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor
from sklearn.neural_network import MLPRegressor

In [15]:
# XGB REGRESSOR

xgb_model = XGBRegressor(
    objective='reg:squarederror',
    random_state=42,
    missing=np.nan,           
    enable_categorical=True   
)

param_grid_xgb = {
    'n_estimators': [300, 500],
    'max_depth': [5, 7, 9],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0]
}

grid_search_xgb = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid_xgb,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)
grid_search_xgb.fit(X_train, y_train)

best_xgb_model = grid_search_xgb.best_estimator_
print("Best params:", grid_search_xgb.best_params_)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

Best params: {'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 300, 'subsample': 1.0}

In [16]:
# LGBM REGRESSOR

import optuna
from sklearn.model_selection import cross_val_score, KFold
import logging

def lgbm_objective(trial):
    params = {
        # Search space
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 20, 100),
        'boosting_type': 'gbdt',
        'verbose': -1,
        'random_state': 42,
        'n_jobs': -1 # Let LightGBM use all cores
    }
    
    model = LGBMRegressor(**params)
    
    # Example using 5-fold CV for speed during tuning
    cv = KFold(n_splits=5, shuffle=True, random_state=42)
    scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='neg_mean_squared_error', n_jobs=1)
    
    return scores.mean()

study_lgbm = optuna.create_study(direction='maximize')
study_lgbm.optimize(lgbm_objective, n_trials=150, show_progress_bar=False) 

print("Best params:", study_lgbm.best_params)

[I 2026-03-30 16:02:56,307] A new study created in memory with name: no-name-d6f77a9b-c8cf-44b8-9e6e-a29fe7d74687
[I 2026-03-30 16:03:02,917] Trial 0 finished with value: -43.44932206482934 and parameters: {'n_estimators': 259, 'learning_rate': 0.17795946196765802, 'num_leaves': 55}. Best is trial 0 with value: -43.44932206482934.
[I 2026-03-30 16:03:04,958] Trial 1 finished with value: -43.02645573383893 and parameters: {'n_estimators': 247, 'learning_rate': 0.10078931745539338, 'num_leaves': 23}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:09,139] Trial 2 finished with value: -44.93990716292189 and parameters: {'n_estimators': 227, 'learning_rate': 0.04497863490526672, 'num_leaves': 56}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:14,117] Trial 3 finished with value: -47.61386156668939 and parameters: {'n_estimators': 297, 'learning_rate': 0.024214682716518707, 'num_leaves': 65}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:16,756] Trial 4 finished with value: -45.78587144232426 and parameters: {'n_estimators': 252, 'learning_rate': 0.04118392242008491, 'num_leaves': 34}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:19,918] Trial 5 finished with value: -49.84394765322254 and parameters: {'n_estimators': 204, 'learning_rate': 0.02739966491166717, 'num_leaves': 95}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:22,404] Trial 6 finished with value: -43.02956505521402 and parameters: {'n_estimators': 274, 'learning_rate': 0.08688240405375157, 'num_leaves': 29}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:23,913] Trial 7 finished with value: -43.77398644234826 and parameters: {'n_estimators': 100, 'learning_rate': 0.19308764308431905, 'num_leaves': 87}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:25,362] Trial 8 finished with value: -46.26882926628163 and parameters: {'n_estimators': 100, 'learning_rate': 0.08587430551132638, 'num_leaves': 92}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:25,936] Trial 9 finished with value: -63.64620103942766 and parameters: {'n_estimators': 59, 'learning_rate': 0.050583636987697786, 'num_leaves': 34}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:27,464] Trial 10 finished with value: -97.36421381238006 and parameters: {'n_estimators': 163, 'learning_rate': 0.010443654554609131, 'num_leaves': 21}. Best is trial 1 with value: -43.02645573383893.
[I 2026-03-30 16:03:29,338] Trial 11 finished with value: -42.67108267091824 and parameters: {'n_estimators': 299, 'learning_rate': 0.10744741996886058, 'num_leaves': 22}. Best is trial 11 with value: -42.67108267091824.
[I 2026-03-30 16:03:32,871] Trial 12 finished with value: -43.19851668063283 and parameters: {'n_estimators': 297, 'learning_rate': 0.09864552517378988, 'num_leaves': 46}. Best is trial 11 with value: -42.67108267091824.
[I 2026-03-30 16:03:33,934] Trial 13 finished with value: -44.047129368858904 and parameters: {'n_estimators': 175, 'learning_rate': 0.11857225500716796, 'num_leaves': 23}. Best is trial 11 with value: -42.67108267091824.
[I 2026-03-30 16:03:36,346] Trial 14 finished with value: -43.88374600963111 and parameters: {'n_estimators': 226, 'learning_rate': 0.06753337618239427, 'num_leaves': 43}. Best is trial 11 with value: -42.67108267091824.
[I 2026-03-30 16:03:39,436] Trial 15 finished with value: -42.549152854990304 and parameters: {'n_estimators': 201, 'learning_rate': 0.14199691344921167, 'num_leaves': 77}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:41,573] Trial 16 finished with value: -43.317133078722335 and parameters: {'n_estimators': 143, 'learning_rate': 0.13877459323188135, 'num_leaves': 74}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:44,670] Trial 17 finished with value: -43.09226233640129 and parameters: {'n_estimators': 189, 'learning_rate': 0.14871833012056881, 'num_leaves': 77}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:46,666] Trial 18 finished with value: -46.54759066874605 and parameters: {'n_estimators': 138, 'learning_rate': 0.05904267103208612, 'num_leaves': 79}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:49,971] Trial 19 finished with value: -48.863081484483295 and parameters: {'n_estimators': 207, 'learning_rate': 0.028495949551597163, 'num_leaves': 66}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:51,554] Trial 20 finished with value: -46.57894205168716 and parameters: {'n_estimators': 116, 'learning_rate': 0.07208482511050342, 'num_leaves': 47}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:53,836] Trial 21 finished with value: -43.13087500514966 and parameters: {'n_estimators': 242, 'learning_rate': 0.10848843207995193, 'num_leaves': 29}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:56,299] Trial 22 finished with value: -43.004647685243356 and parameters: {'n_estimators': 276, 'learning_rate': 0.140557850768817, 'num_leaves': 36}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:03:59,061] Trial 23 finished with value: -43.10280193252454 and parameters: {'n_estimators': 276, 'learning_rate': 0.14146360447060252, 'num_leaves': 36}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:03,449] Trial 24 finished with value: -43.110463084913256 and parameters: {'n_estimators': 277, 'learning_rate': 0.17706757422560082, 'num_leaves': 84}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:07,914] Trial 25 finished with value: -43.26092333641653 and parameters: {'n_estimators': 298, 'learning_rate': 0.1264952430514443, 'num_leaves': 69}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:10,213] Trial 26 finished with value: -43.853863083898375 and parameters: {'n_estimators': 214, 'learning_rate': 0.19879692624511416, 'num_leaves': 39}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:13,598] Trial 27 finished with value: -63.86277071379402 and parameters: {'n_estimators': 269, 'learning_rate': 0.01042737634116372, 'num_leaves': 52}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:15,412] Trial 28 finished with value: -43.76860405633463 and parameters: {'n_estimators': 230, 'learning_rate': 0.07998464223177566, 'num_leaves': 28}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:18,902] Trial 29 finished with value: -43.00420447982695 and parameters: {'n_estimators': 254, 'learning_rate': 0.15910457092289076, 'num_leaves': 52}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:21,606] Trial 30 finished with value: -43.07393672639143 and parameters: {'n_estimators': 190, 'learning_rate': 0.16776692778028554, 'num_leaves': 62}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:25,207] Trial 31 finished with value: -43.06166611616134 and parameters: {'n_estimators': 260, 'learning_rate': 0.15613309767857522, 'num_leaves': 53}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:29,111] Trial 32 finished with value: -42.804076844912046 and parameters: {'n_estimators': 285, 'learning_rate': 0.12299867479500465, 'num_leaves': 57}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:32,375] Trial 33 finished with value: -43.606155093685715 and parameters: {'n_estimators': 244, 'learning_rate': 0.11472551263349588, 'num_leaves': 56}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:36,678] Trial 34 finished with value: -42.850068183258074 and parameters: {'n_estimators': 291, 'learning_rate': 0.11150748556684971, 'num_leaves': 71}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:40,857] Trial 35 finished with value: -42.93181796619027 and parameters: {'n_estimators': 288, 'learning_rate': 0.10357067354897169, 'num_leaves': 69}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:45,232] Trial 36 finished with value: -45.06354175298517 and parameters: {'n_estimators': 300, 'learning_rate': 0.038800799755635655, 'num_leaves': 100}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:48,817] Trial 37 finished with value: -42.73280130137037 and parameters: {'n_estimators': 263, 'learning_rate': 0.09321869048337035, 'num_leaves': 73}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:52,834] Trial 38 finished with value: -44.134139497083666 and parameters: {'n_estimators': 262, 'learning_rate': 0.05925303878950539, 'num_leaves': 83}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:04:56,338] Trial 39 finished with value: -43.68263786939666 and parameters: {'n_estimators': 234, 'learning_rate': 0.09365831252731298, 'num_leaves': 59}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:05:01,054] Trial 40 finished with value: -51.944048953136345 and parameters: {'n_estimators': 285, 'learning_rate': 0.016923316455433504, 'num_leaves': 88}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:05:05,084] Trial 41 finished with value: -42.847205805688205 and parameters: {'n_estimators': 287, 'learning_rate': 0.08160436356877952, 'num_leaves': 74}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:05:19,133] Trial 42 finished with value: -43.31405094394179 and parameters: {'n_estimators': 264, 'learning_rate': 0.07832599849145956, 'num_leaves': 78}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:05:23,509] Trial 43 finished with value: -42.910549778962 and parameters: {'n_estimators': 284, 'learning_rate': 0.08867797628412989, 'num_leaves': 74}. Best is trial 15 with value: -42.549152854990304.
[I 2026-03-30 16:05:27,207] Trial 44 finished with value: -42.46577502593692 and parameters: {'n_estimators': 246, 'learning_rate': 0.12750975670323422, 'num_leaves': 64}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:30,328] Trial 45 finished with value: -42.90718836332498 and parameters: {'n_estimators': 216, 'learning_rate': 0.129887695122297, 'num_leaves': 64}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:33,959] Trial 46 finished with value: -43.065665311829186 and parameters: {'n_estimators': 244, 'learning_rate': 0.1020555642050786, 'num_leaves': 59}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:40,362] Trial 47 finished with value: -43.52090326358931 and parameters: {'n_estimators': 195, 'learning_rate': 0.11996175181347125, 'num_leaves': 82}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:44,269] Trial 48 finished with value: -43.425309565623316 and parameters: {'n_estimators': 252, 'learning_rate': 0.062206317963022666, 'num_leaves': 92}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:44,874] Trial 49 finished with value: -47.33139845198319 and parameters: {'n_estimators': 51, 'learning_rate': 0.16738547531844977, 'num_leaves': 47}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:48,656] Trial 50 finished with value: -45.85858108456545 and parameters: {'n_estimators': 268, 'learning_rate': 0.037622550592261786, 'num_leaves': 66}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:53,286] Trial 51 finished with value: -42.67288827383511 and parameters: {'n_estimators': 283, 'learning_rate': 0.09624207889590478, 'num_leaves': 74}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:05:56,284] Trial 52 finished with value: -46.99003578178777 and parameters: {'n_estimators': 158, 'learning_rate': 0.05125397990511642, 'num_leaves': 76}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:06:00,376] Trial 53 finished with value: -42.82469551765595 and parameters: {'n_estimators': 276, 'learning_rate': 0.09673596806827915, 'num_leaves': 70}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:06:17,256] Trial 54 finished with value: -43.084371817981015 and parameters: {'n_estimators': 238, 'learning_rate': 0.13325931479280206, 'num_leaves': 80}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:06:42,927] Trial 55 finished with value: -43.2872525668068 and parameters: {'n_estimators': 255, 'learning_rate': 0.11950401061469783, 'num_leaves': 87}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:06:48,109] Trial 56 finished with value: -44.566246317579306 and parameters: {'n_estimators': 175, 'learning_rate': 0.07018950561825547, 'num_leaves': 73}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:06:56,150] Trial 57 finished with value: -43.629028619664645 and parameters: {'n_estimators': 223, 'learning_rate': 0.18850212606984304, 'num_leaves': 62}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:02,072] Trial 58 finished with value: -43.43657184281609 and parameters: {'n_estimators': 270, 'learning_rate': 0.14774618802853637, 'num_leaves': 66}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:04,720] Trial 59 finished with value: -42.84360232783413 and parameters: {'n_estimators': 281, 'learning_rate': 0.08641489949537459, 'num_leaves': 25}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:05,802] Trial 60 finished with value: -46.693277550341705 and parameters: {'n_estimators': 73, 'learning_rate': 0.10475673096069947, 'num_leaves': 81}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:10,334] Trial 61 finished with value: -42.78393256972659 and parameters: {'n_estimators': 293, 'learning_rate': 0.09347551534744374, 'num_leaves': 70}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:15,065] Trial 62 finished with value: -43.18949487225426 and parameters: {'n_estimators': 297, 'learning_rate': 0.0749539599282913, 'num_leaves': 68}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:18,145] Trial 63 finished with value: -43.12410574307335 and parameters: {'n_estimators': 293, 'learning_rate': 0.12943896183730716, 'num_leaves': 42}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:22,449] Trial 64 finished with value: -42.7299430655474 and parameters: {'n_estimators': 278, 'learning_rate': 0.11315349577569807, 'num_leaves': 71}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:26,428] Trial 65 finished with value: -43.094253577138105 and parameters: {'n_estimators': 251, 'learning_rate': 0.09696657675992652, 'num_leaves': 72}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:31,683] Trial 66 finished with value: -43.689858355512214 and parameters: {'n_estimators': 272, 'learning_rate': 0.08813548047708576, 'num_leaves': 76}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:35,952] Trial 67 finished with value: -43.57634161110534 and parameters: {'n_estimators': 260, 'learning_rate': 0.06423346388277747, 'num_leaves': 63}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:40,709] Trial 68 finished with value: -43.110112884178875 and parameters: {'n_estimators': 278, 'learning_rate': 0.10910857566934917, 'num_leaves': 67}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:45,452] Trial 69 finished with value: -43.78876586951384 and parameters: {'n_estimators': 300, 'learning_rate': 0.05077775441974711, 'num_leaves': 85}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:48,659] Trial 70 finished with value: -43.08226632872954 and parameters: {'n_estimators': 206, 'learning_rate': 0.14908708936961296, 'num_leaves': 78}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:50,466] Trial 71 finished with value: -42.476179080734155 and parameters: {'n_estimators': 291, 'learning_rate': 0.11981138821396714, 'num_leaves': 20}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:52,351] Trial 72 finished with value: -42.84279091711947 and parameters: {'n_estimators': 293, 'learning_rate': 0.11436887222774318, 'num_leaves': 20}. Best is trial 44 with value: -42.46577502593692.
[I 2026-03-30 16:07:54,006] Trial 73 finished with value: -42.03752961466638 and parameters: {'n_estimators': 265, 'learning_rate': 0.13317485108417282, 'num_leaves': 23}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:07:56,277] Trial 74 finished with value: -43.388781037116146 and parameters: {'n_estimators': 262, 'learning_rate': 0.18235073552932315, 'num_leaves': 31}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:07:58,084] Trial 75 finished with value: -42.41728945985552 and parameters: {'n_estimators': 267, 'learning_rate': 0.1380475812118924, 'num_leaves': 23}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:07:59,908] Trial 76 finished with value: -43.31966499327651 and parameters: {'n_estimators': 282, 'learning_rate': 0.14295960512550873, 'num_leaves': 23}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:02,668] Trial 77 finished with value: -42.22771624375135 and parameters: {'n_estimators': 272, 'learning_rate': 0.15923868709173, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:04,957] Trial 78 finished with value: -42.248967381559666 and parameters: {'n_estimators': 270, 'learning_rate': 0.16525647079646927, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:06,706] Trial 79 finished with value: -42.50033137148534 and parameters: {'n_estimators': 233, 'learning_rate': 0.166799943530244, 'num_leaves': 23}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:08,521] Trial 80 finished with value: -42.978493511971045 and parameters: {'n_estimators': 226, 'learning_rate': 0.16545833893007617, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:10,453] Trial 81 finished with value: -42.56053548005928 and parameters: {'n_estimators': 239, 'learning_rate': 0.15565323416272706, 'num_leaves': 31}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:12,652] Trial 82 finished with value: -43.21546621605495 and parameters: {'n_estimators': 239, 'learning_rate': 0.1561777794738554, 'num_leaves': 33}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:14,158] Trial 83 finished with value: -42.23780294289692 and parameters: {'n_estimators': 217, 'learning_rate': 0.1769371851303544, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:15,476] Trial 84 finished with value: -43.74176153795444 and parameters: {'n_estimators': 200, 'learning_rate': 0.19971956721934586, 'num_leaves': 22}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:16,996] Trial 85 finished with value: -42.493312720241946 and parameters: {'n_estimators': 213, 'learning_rate': 0.17539898409543642, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:18,833] Trial 86 finished with value: -42.37528775263286 and parameters: {'n_estimators': 215, 'learning_rate': 0.17417051531301733, 'num_leaves': 26}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:20,420] Trial 87 finished with value: -42.53206426423333 and parameters: {'n_estimators': 213, 'learning_rate': 0.17852478280115058, 'num_leaves': 27}. Best is trial 73 with value: -42.03752961466638.
[I 2026-03-30 16:08:22,393] Trial 88 finished with value: -42.470347975063106 and parameters: {'n_estimators': 221, 'learning_rate': 0.17909823806799136, 'num_leaves': 25}. Best is trial 73 with value: -42.03752961466638.

Best params: {'n_estimators': 207, 'learning_rate': 0.1737559988817346, 'num_leaves': 27}

I implemented the optuna hyperparameter tuning for lightgbm, and it is giving me a good boost in the performance. I will implement it for xgboost as well, and then move on to the imputation part. I implemented the optuna hyperparameter tuning, because the gridsearchcv was taking a lot of time to run, like 5 candidates initialization in gridsearchcv was taking around 5.37 ish minutes, and I had around 125+ candidates to try. So optune is a good choice for hyperparameter tuning in this case, because it is much faster than gridsearchcv, and it also gives better results. I will not implement it to others (for now), if situation arises, I will turn to optuna.

In [ ]:
# CATBOOST REGRESSOR

from catboost import CatBoostRegressor

catboost_model = CatBoostRegressor(random_state=42, verbose=0)

param_grid_catboost = {'iterations': [500, 800], 'depth': [6,8,10],
              'learning_rate': [0.05, 0.1], 'subsample': [0.8, 1.0]}

grid_catboost = GridSearchCV(catboost_model, param_grid_catboost, cv=5, scoring='r2', n_jobs=-1, verbose=1)
grid_catboost.fit(X_train, y_train)
best_catboost_model = grid_catboost.best_estimator_

Fitting 5 folds for each of 24 candidates, totalling 120 fits

In [ ]:
# GRADIENT BOOSTING REGRESSOR

from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(random_state=42)

param_grid_gbr = {'n_estimators': [300, 500], 'max_depth': [5,7],
              'learning_rate': [0.05, 0.1]}

grid_gradient_boost = GridSearchCV(model, param_grid_gbr, cv=5, scoring='r2', n_jobs=-1, verbose=1)
grid_gradient_boost.fit(X_train_imputed, y_train)
best_model_gradient_boost = grid_gradient_boost.best_estimator_

In [ ]:
# RANDOMFOREST REGRESSOR

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42, n_jobs=-1)

param_grid_rf = {'n_estimators': [200, 300], 'max_depth': [10, 15, 20],
              'min_samples_split': [2, 5]}

grid_random_forest = GridSearchCV(model, param_grid_rf, cv=5, scoring='r2', n_jobs=-1, verbose=1)
grid_random_forest.fit(X_train_imputed, y_train)
best_model_rf = grid_random_forest.best_estimator_

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred):
    return {
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "MSE": mean_squared_error(y_true, y_pred),
        "MAE": mean_absolute_error(y_true, y_pred),
        "R2 Score": r2_score(y_true, y_pred)
    }

In [ ]:
y_pred_xgb = best_xgb_model.predict(X_test)

xgb_eval = evaluate_model(y_test, y_pred_xgb)

print(xgb_eval)

In [ ]:
y_pred_catboost = best_catboost_model.predict(X_test)

catboost_eval = evaluate_model(y_test, y_pred_catboost)

print(catboost_eval)

In [ ]:
best_lgbm_params = study.best_params

lgbm_model = LGBMRegressor(
    boosting_type="gbdt",
    random_state=42,
    verbose=-1,
    **best_lgbm_params
)

lgbm_model.fit(X_train, y_train)

y_pred_lgbm = lgbm_model.predict(X_test)

lgbm_eval = evaluate_model(y_test, y_pred_lgbm)

print(lgbm_eval)

In [ ]:
y_pred_gradient_boost = best_model_gradient_boost.predict(X_test_imputed)

gradient_boost_eval = evaluate_model(y_test ,y_pred_gradient_boost)

print(gradient_boost_eval)

In [ ]:
y_pred_rf = best_model_rf.predict(X_test_imputed)

rf_eval = evaluate_model(y_test, y_pred_rf)

print(rf_eval)